// Database types - will be auto-generated by Supabase CLI in production
// Run: npx supabase gen types typescript --project-id <project-id> > src/types/database.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type MemberRole = "owner" | "admin" | "member";
export type InviteStatus = "pending" | "accepted" | "expired";
export type MessageRole = "user" | "assistant" | "system";
export type SubscriptionStatus =
  | "active"
  | "canceled"
  | "past_due"
  | "trialing"
  | "unpaid";
export type PlanType = "none" | "business";

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          email: string;
          name: string | null;
          avatarUrl: string | null;
          createdAt: string;
          updatedAt: string;
        };
        Insert: {
          id: string;
          email: string;
          name?: string | null;
          avatarUrl?: string | null;
          createdAt?: string;
          updatedAt?: string;
        };
        Update: {
          id?: string;
          email?: string;
          name?: string | null;
          avatarUrl?: string | null;
          updatedAt?: string;
        };
      };
      organizations: {
        Row: {
          id: string;
          name: string;
          slug: string;
          logoUrl: string | null;
          createdBy: string;
          createdAt: string;
          updatedAt: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          logoUrl?: string | null;
          createdBy: string;
          createdAt?: string;
          updatedAt?: string;
        };
        Update: {
          name?: string;
          slug?: string;
          logoUrl?: string | null;
          updatedAt?: string;
        };
      };
      organization_members: {
        Row: {
          id: string;
          organizationId: string;
          userId: string;
          role: MemberRole;
          joinedAt: string;
        };
        Insert: {
          id?: string;
          organizationId: string;
          userId: string;
          role?: MemberRole;
          joinedAt?: string;
        };
        Update: {
          role?: MemberRole;
        };
      };
      organization_invites: {
        Row: {
          id: string;
          organizationId: string;
          email: string;
          role: MemberRole;
          token: string;
          status: InviteStatus;
          invitedBy: string;
          expiresAt: string;
          createdAt: string;
        };
        Insert: {
          id?: string;
          organizationId: string;
          email: string;
          role?: MemberRole;
          token: string;
          status?: InviteStatus;
          invitedBy: string;
          expiresAt: string;
          createdAt?: string;
        };
        Update: {
          status?: InviteStatus;
        };
      };
      chat_threads: {
        Row: {
          id: string;
          organizationId: string;
          userId: string;
          title: string | null;
          createdAt: string;
          updatedAt: string;
        };
        Insert: {
          id?: string;
          organizationId: string;
          userId: string;
          title?: string | null;
          createdAt?: string;
          updatedAt?: string;
        };
        Update: {
          title?: string | null;
          updatedAt?: string;
        };
      };
      chat_messages: {
        Row: {
          id: string;
          threadId: string;
          role: MessageRole;
          content: string;
          metadata: Json;
          createdAt: string;
        };
        Insert: {
          id?: string;
          threadId: string;
          role: MessageRole;
          content: string;
          metadata?: Json;
          createdAt?: string;
        };
        Update: {
          content?: string;
          metadata?: Json;
        };
      };
      subscriptions: {
        Row: {
          id: string;
          organizationId: string;
          stripeCustomerId: string | null;
          stripeSubscriptionId: string | null;
          plan: PlanType;
          status: SubscriptionStatus;
          currentPeriodStart: string | null;
          currentPeriodEnd: string | null;
          cancelAtPeriodEnd: boolean;
          createdAt: string;
          updatedAt: string;
        };
        Insert: {
          id?: string;
          organizationId: string;
          stripeCustomerId?: string | null;
          stripeSubscriptionId?: string | null;
          plan?: PlanType;
          status?: SubscriptionStatus;
          currentPeriodStart?: string | null;
          currentPeriodEnd?: string | null;
          cancelAtPeriodEnd?: boolean;
          createdAt?: string;
          updatedAt?: string;
        };
        Update: {
          stripeCustomerId?: string | null;
          stripeSubscriptionId?: string | null;
          plan?: PlanType;
          status?: SubscriptionStatus;
          currentPeriodStart?: string | null;
          currentPeriodEnd?: string | null;
          cancelAtPeriodEnd?: boolean;
          updatedAt?: string;
        };
      };
      usage: {
        Row: {
          id: string;
          organizationId: string;
          month: string;
          messagesCount: number;
          tokensUsed: number;
          filesUploaded: number;
          storageBytes: number;
        };
        Insert: {
          id?: string;
          organizationId: string;
          month: string;
          messagesCount?: number;
          tokensUsed?: number;
          filesUploaded?: number;
          storageBytes?: number;
        };
        Update: {
          messagesCount?: number;
          tokensUsed?: number;
          filesUploaded?: number;
          storageBytes?: number;
        };
      };
      documents: {
        Row: {
          id: string;
          organizationId: string;
          title: string;
          content: string | null;
          fileUrl: string | null;
          fileType: string | null;
          metadata: Json;
          createdBy: string;
          createdAt: string;
          updatedAt: string;
        };
        Insert: {
          id?: string;
          organizationId: string;
          title: string;
          content?: string | null;
          fileUrl?: string | null;
          fileType?: string | null;
          metadata?: Json;
          createdBy: string;
          createdAt?: string;
          updatedAt?: string;
        };
        Update: {
          title?: string;
          content?: string | null;
          fileUrl?: string | null;
          metadata?: Json;
          updatedAt?: string;
        };
      };
      embeddings: {
        Row: {
          id: string;
          documentId: string;
          organizationId: string;
          content: string;
          embedding: number[] | null;
          metadata: Json;
          createdAt: string;
        };
        Insert: {
          id?: string;
          documentId: string;
          organizationId: string;
          content: string;
          embedding?: number[] | null;
          metadata?: Json;
          createdAt?: string;
        };
        Update: {
          content?: string;
          embedding?: number[] | null;
          metadata?: Json;
        };
      };
    };
    Functions: {
      match_embeddings: {
        Args: {
          query_embedding: number[];
          p_organizationId: string;
          match_count?: number;
          match_threshold?: number;
        };
        Returns: {
          id: string;
          documentId: string;
          content: string;
          metadata: Json;
          similarity: number;
        }[];
      };
      increment_usage: {
        Args: {
          p_organizationId: string;
          p_messages?: number;
          p_tokens?: number;
          p_files?: number;
          p_storage?: number;
        };
        Returns: void;
      };
    };
  };
}

// Helper types
export type Tables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Row"];
export type Insertable<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Insert"];
export type Updateable<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Update"];
